### ISSUE TITLE
Clean up of archive: keywords

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/elife-vendor-workflow-config#82]
eg differences:
e.coli
E.coli
E. coli
e. coli
E. Coli
`<italics>E. coli</italics>`

etc

There are others too. I'll ask Sian/Nathan for the database info so we in editorial and production can start working out the extent of the problem!

**Comment by gnott** [comment]
Ok to close this @Melissa37 ? I'm just going through looking at issues assigned to me and not closed.

**Comment by Melissa37** [comment]
Yup, thanks
